# SQL SERVER
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://LAPTOP-VF70175T;databasename=marriott
    username: Alexander
    password: 12345678
  jpa:
    database: sql-server
    hibernate:
      ddl-auto: update
    show-sql: false
  
server:
  port: 8081
  