# SQL SERVER
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:51560;databasename=marriott
    username: sa
    password: paccbet&2@
  jpa:
    database: sql-server
    hibernate:
      ddl-auto: update
    show-sql: false
 
server:
  port: 8082