# SQL SERVER
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databasename=marriott
    username: sa
    password: 1234
  jpa:
    database: sql-server
    hibernate:
      ddl-auto: update
    show-sql: false
  
server:
  port: 8079